In [10]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import requests

## Data Collection

### Files sources

In [11]:
# URLs of the files
train_datas_url = 'https://www.raphaelcousin.com/modules/data-science-practice/module4/exercise/module4_exercise_train.zip'
test_data_url = 'https://www.raphaelcousin.com/modules/data-science-practice/module4/exercise/Neighborhood_Market_data.csv'

# Function to download a file
def download_file(url, file_name):
    response = requests.get(url)
    response.raise_for_status()  # Ensure we notice bad responses
    with open(file_name, 'wb') as file:
        file.write(response.content)
    print(f'Downloaded {file_name} from {url}')

# Downloading the files
download_file(train_datas_url, 'module4_exercise_train.zip')
download_file(test_data_url, 'Neighborhood_Market_data.csv')

Downloaded module4_exercise_train.zip from https://www.raphaelcousin.com/modules/data-science-practice/module4/exercise/module4_exercise_train.zip
Downloaded Neighborhood_Market_data.csv from https://www.raphaelcousin.com/modules/data-science-practice/module4/exercise/Neighborhood_Market_data.csv

In [12]:
import zipfile
import os

#extract_dir = "module4_exercise_train" # 创建目录
#os.makedirs(extract_dir, exist_ok=True)

with zipfile.ZipFile("module4_exercise_train.zip", 'r') as zip_ref:
    zip_ref.extractall("module4_exercise_train") # 提取到目录

#### CityMart

In [13]:
# read "CityMart_data.csv"
df_citymart = pd.read_csv('CityMart_data.csv', index_col='item_code')
print(df_citymart.shape)
df_citymart.head()

(415, 10)

,store_name,mass,dimension_length,dimension_width,dimension_height,days_since_last_purchase,package_volume,stock_age,quantity_sold,last_modified
item_code,,,,,,,,,,
P0019,CityMart,2.81,26.83,38.75,24.89,323,25877.199625,253,202,2023-01-19
P0024,CityMart,3.30,59.23,34.99,21.78,321,45138.128706,21,225,2023-01-24
P0025,CityMart,2.34,22.60,16.90,60.12,291,22962.232800,316,278,2023-01-25
P0034,CityMart,6.54,18.59,68.72,21.99,126,28092.330552,612,233,2023-02-03
P0039,CityMart,9.94,57.89,88.33,35.45,312,181270.870165,968,203,2023-02-08

#### Greenfield_Grocers

In [14]:
# read "Greenfield_Grocers_data.csv"
df_greenfield = pd.read_csv('Greenfield_Grocers_data.csv', skiprows=2, sep= '|')
df_greenfield.columns = df_greenfield.iloc[0] # 将第一行替换为列名
df_greenfield = df_greenfield[1:] # 删除第一行
df_greenfield = df_greenfield.iloc[:, :-2] # 手动选择所有行和除最后两列以外的所有列
df_greenfield.columns = [col.lower() for col in df_greenfield.columns] # 切换小写列名
df_greenfield.set_index('item_code', inplace=True) # 设置item_code为索引
print(df_greenfield.shape)
df_greenfield.head()

(401, 10)

,store_name,mass,dimension_length,dimension_width,dimension_height,days_since_last_purchase,package_volume,stock_age,quantity_sold,last_modified
item_code,,,,,,,,,,
P0006,Greenfield_Grocers,5.02,86.68,71.64,16.42,66,101964.18038400002,450,130,2023-01-06
P0014,Greenfield_Grocers,9.91,21.67,54.91,84.8,99,100903.49455999999,827,118,2023-01-14
P0016,Greenfield_Grocers,1.13,60.03,97.39,90.0,348,526168.953,981,136,2023-01-16
P0021,Greenfield_Grocers,0.95,40.36,67.91,99.76,301,273426.95657599997,289,155,2023-01-21
P0028,Greenfield_Grocers,5.24,22.37,61.78,68.67,15,94903.217262,423,177,2023-01-28

#### Outlet_data

In [15]:
# read "SuperSaver_Outlet_data.xlsx"
df_outlets = pd.read_excel('SuperSaver_Outlet_data.xlsx', sheet_name=None)
df_outlets['Info'].columns = df_outlets['Info'].columns[1:].tolist() + [None]
df_outlets['Info'].columns = df_outlets['Info'].columns.str.replace(' ', '_')
df_outlet = pd.merge(df_outlets['Quantity'], df_outlets['Info'], left_on='item_code', right_on='item_code')
df_outlet = df_outlet.iloc[:, :-1]
df_outlet.set_index('item_code', inplace=True)
print(df_outlet.shape)
df_outlet.head()

(379, 9)

,quantity_sold,store_name,mass,dimension_length,dimension_width,dimension_height,days_since_last_purchase,package_volume,stock_age
item_code,,,,,,,,,
P0003,198,SuperSaver_Outlet,2.40,50.90,8.80,68.82,337,30825.854400,277
P0007,211,SuperSaver_Outlet,9.88,43.65,48.64,55.78,16,118428.526080,291
P0008,200,SuperSaver_Outlet,1.45,36.18,10.23,69.14,315,25590.193596,169
P0009,209,SuperSaver_Outlet,6.98,48.13,45.55,44.66,295,97909.078190,443
P0012,186,SuperSaver_Outlet,7.20,23.66,65.90,12.05,40,18788.287700,45

#### HighStreet_Bazaar

In [16]:
# read 'HighStreet_Bazaar_data.json'
df_highstreet = pd.read_json('HighStreet_Bazaar_data.json')
df_highstreet.set_index('item_code', inplace=True)
print(f"HighStreet_Bazaar data shape: {df_highstreet.shape}")
df_highstreet.head()

HighStreet_Bazaar data shape: (396, 10)

,store_name,mass,dimension_length,dimension_width,dimension_height,days_since_last_purchase,package_volume,stock_age,quantity_sold,last_modified
item_code,,,,,,,,,,
P0001,HighStreet_Bazaar,6.11,75.46,91.62,92.08,78.0,636608.450016,237,346,1672531200000
P0011,HighStreet_Bazaar,4.34,16.97,93.21,54.58,344.0,86333.208546,184,218,1673395200000
P0015,HighStreet_Bazaar,1.37,58.93,11.28,73.87,344.0,49103.634648,946,315,1673740800000
P0017,HighStreet_Bazaar,7.27,51.51,39.21,16.17,138.0,32658.663807,268,228,1673913600000
P0020,HighStreet_Bazaar,0.89,57.50,69.84,6.12,333.0,24576.696000,396,228,1674172800000

#### Aggregate

In [17]:
data = pd.concat([df_citymart, df_greenfield, df_outlet, df_highstreet], axis=0)
print(data.shape)
data.head()

(1591, 10)

,store_name,mass,dimension_length,dimension_width,dimension_height,days_since_last_purchase,package_volume,stock_age,quantity_sold,last_modified
item_code,,,,,,,,,,
P0019,CityMart,2.81,26.83,38.75,24.89,323,25877.199625,253,202,2023-01-19
P0024,CityMart,3.3,59.23,34.99,21.78,321,45138.128706,21,225,2023-01-24
P0025,CityMart,2.34,22.6,16.9,60.12,291,22962.2328,316,278,2023-01-25
P0034,CityMart,6.54,18.59,68.72,21.99,126,28092.330552,612,233,2023-02-03
P0039,CityMart,9.94,57.89,88.33,35.45,312,181270.870165,968,203,2023-02-08

#### Simple baseline

In [18]:
from sklearn.model_selection import KFold
from sklearn.metrics import mean_absolute_error, accuracy_score
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import numpy as np

def get_simple_baseline(data, fillna_value=-1, drop_cols=None, k_fold=5, scaler='standard', model='linear', metric='mae', target_col=None, X_data_test=None):

    data = data.copy()
    # Handle missing values
    data.fillna(fillna_value, inplace=True)
    if X_data_test is not None:
        X_data_test = X_data_test.copy()
        X_data_test.fillna(fillna_value, inplace=True)

    # Drop unwanted columns
    if drop_cols:
        data.drop(drop_cols, axis=1, inplace=True)
        if X_data_test is not None:
            X_data_test.drop(drop_cols, axis=1, inplace=True)

    # Split data into features (X) and target (y)
    y = data[target_col]
    X = data.drop(target_col, axis=1)

    # Feature scaling
    if scaler == 'standard':
        scaler = StandardScaler()
    elif scaler == 'minmax':
        scaler = MinMaxScaler()
    else:
        scaler = None

    if scaler:
        X = scaler.fit_transform(X)
        if X_data_test is not None:
            X_data_test = scaler.transform(X_data_test)

    # Initialize the model
    if model == 'linear':
        model = LinearRegression()
    elif model == 'logistic':
        model = LogisticRegression()
    elif model == 'random_forest':
        model = RandomForestClassifier()
    else:
        raise ValueError("Unsupported model type")

    # Initialize cross-validation
    kf = KFold(n_splits=k_fold, shuffle=True, random_state=42)
    scores = []

    # Train and evaluate using k-fold cross-validation
    for train_index, test_index in kf.split(X):
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]

        # Train the model
        model.fit(X_train, y_train)

        # Make predictions
        y_pred = model.predict(X_test)

        # Evaluate using the specified metric
        if metric == 'mae':
            score = mean_absolute_error(y_test, y_pred)
        elif metric == 'accuracy':
            score = accuracy_score(y_test, np.round(y_pred))
        else:
            raise ValueError("Unsupported metric")

        scores.append(score)

    if X_data_test is not None:
        model.fit(X, y)
        return np.mean(scores), model.predict(X_data_test)

    # Return the average score
    return np.mean(scores)

In [19]:
get_simple_baseline(data, fillna_value=-1, drop_cols=['store_name', 'last_modified'], k_fold=5, scaler='standard', model='linear', metric='mae', target_col='quantity_sold')

45.04056766700087

### API sources

In [20]:
def get_api(endpoint_url):
    try:
        # Make the GET request to the mock API
        response = requests.get(endpoint_url)

        if response.status_code == 200:
            data = response.json()
            print(data["message"])
            return data['data']
        else:
            print(f"Failed to retrieve volume data. Status code: {response.status_code}")

    except Exception as e:
        print(f"An error occurred: {e}")
# password =
# prices =

In [21]:
password = get_api("https://www.raphaelcousin.com/api/course/auth")["password"]
prices = get_api(f"https://www.raphaelcousin.com/api/course/{password}/volumes")
prices

Authentication successful
Volume data retrieved successfully

{'P0001': 48469.09869,
 'P0002': 11252.96382,
 'P0003': 24725.379062999997,
 'P0004': 8361.648239999999,
 'P0005': 255200.66715,
 'P0006': 644786.0415,
 'P0007': 302122.4971200001,
 'P0008': 314150.164308,
 'P0009': 61847.672796,
 'P0010': 746779.532672,
 'P0011': 239910.083994,
 'P0012': 17482.030523999998,
 'P0013': 10598.364972,
 'P0014': 10520.449939999999,
 'P0015': 136549.7757,
 'P0016': 247934.58020000003,
 'P0017': 54689.528088,
 'P0018': 9057.165282,
 'P0019': 21814.067016,
 'P0020': 454560.15780000004,
 'P0021': 67789.79616,
 'P0022': 39971.18208,
 'P0023': 31282.378228000005,
 'P0024': 80893.19616,
 'P0025': 87468.08641799999,
 'P0026': 17419.922304,
 'P0027': 337530.08437200007,
 'P0028': 74212.37982,
 'P0029': 58495.709272,
 'P0030': 61834.98204000001,
 'P0031': 32930.384384000005,
 'P0032': 69289.19848,
 'P0033': 313977.75333599997,
 'P0034': 6635.3966279999995,
 'P0035': 204784.65251999997,
 'P0036': 345513.98932000005,
 'P0037': 81655.593192,
 'P0038': 102508.70663199997,
 'P0039': 170846.537576,
 'P0040': 210375.733092,
 'P0041': 159665.58820800003,
 'P0042': 5601.562506,
 'P0043': 674903.26211,
 'P0044': 74291.725038,
 'P0045': 94706.35440000001,
 'P0046': 28594.563299999998,
 'P0047': 216364.3677,
 'P0048': 263679.950268,
 'P0049': 114997.376304,
 'P0050': 73084.192176,
 'P0051': 128404.86952799998,
 'P0052': 40038.65316,
 'P0053': 381248.29386000003,
 'P0054': 29803.7565,
 'P0055': 96818.91494399997,
 'P0056': 36868.10832000001,
 'P0057': 127353.90831999999,
 'P0058': 741819.466256,
 'P0059': 91898.76267,
 'P0060': 18903.958560000003,
 'P0061': 77126.40252599999,
 'P0062': 24306.60375,
 'P0063': 30986.164139999993,
 'P0064': 135279.6353,
 'P0065': 566752.4391760001,
 'P0066': 135335.94547200002,
 'P0067': 84321.434912,
 'P0068': 100098.3137,
 'P0069': 68976.896352,
 'P0070': 218897.53775999998,
 'P0071': 21780.690749999998,
 'P0072': 110199.11776000001,
 'P0073': 37649.217552,
 'P0074': 33240.372308,
 'P0075': 316450.24742999993,
 'P0076': 53432.963295999994,
 'P0077': 94808.72226,
 'P0078': 318178.60600500007,
 'P0079': 53024.031788,
 'P0080': 127272.10455,
 'P0081': 66981.830568,
 'P0082': 115315.168904,
 'P0083': 117855.22214400001,
 'P0084': 35906.667552,
 'P0085': 135571.9938,
 'P0086': 565055.299419,
 'P0087': 155038.83703000002,
 'P0088': 23583.755664000004,
 'P0089': 20837.245644000002,
 'P0090': 432231.2091200001,
 'P0091': 28825.127544,
 'P0092': 81555.730872,
 'P0093': 393585.542649,
 'P0094': 362685.21608,
 'P0095': 40319.888896000004,
 'P0096': 169638.054462,
 'P0097': 439731.48273600003,
 'P0098': 74860.81354,
 'P0099': 83425.96937999998,
 'P0100': 548578.4134079999,
 'P0101': 67517.383472,
 'P0102': 61215.831593999996,
 'P0103': 99124.12632,
 'P0104': 58046.07032799999,
 'P0105': 45450.424074999995,
 'P0106': 17532.39015,
 'P0107': 35526.34850000001,
 'P0108': 10740.523169999999,
 'P0109': 353060.07552,
 'P0110': 12592.345487999997,
 'P0111': 503737.204992,
 'P0112': 36285.1468,
 'P0113': 72661.47696,
 'P0114': 23272.957619999997,
 'P0115': 7988.532291000001,
 'P0116': 13993.933727999998,
 'P0117': 41530.821585000005,
 'P0118': 379324.70511,
 'P0119': 121216.35284999998,
 'P0120': 212872.88255999997,
 'P0121': 499518.94104,
 'P0122': 198739.1464,
 'P0123': 130960.39687499999,
 'P0124': 121715.55552000001,
 'P0125': 242265.23367999998,
 'P0126': 16607.31174,
 'P0127': 418824.015534,
 'P0128': 26103.25945,
 'P0129': 320752.47664000007,
 'P0130': 9343.077780000001,
 'P0131': 309844.961088,
 'P0132': 337979.83296,
 'P0133': 356052.06588,
 'P0134': 7769.971440000001,
 'P0135': 345822.46776,
 'P0136': 87850.58892000001,
 'P0137': 46537.62192,
 'P0138': 92465.90053499998,
 'P0139': 171419.476566,
 'P0140': 96901.96592999999,
 'P0141': 108213.057804,
 'P0142': 101932.150056,
 'P0143': 106102.75903199997,
 'P0144': 4975.082112,
 'P0145': 24545.214144,
 'P0146': 206269.168875,
 'P0147': 34284.986331,
 'P0148': 222852.36023400005,
 'P0149': 89481.40502399999,
 'P0150': 5250.995288,
 'P0151': 170997.18386400002,
 'P0152': 63100.80928200001,
 'P0153': 29712.434255999997,
 'P0154': 117778.89042899998,
 'P0155': 8134.83495,
 'P0156': 155918.709056,
 'P0157': 439681.53887999995,
 'P0158': 65388.570898000005,
 'P0159': 249231.101184,
 'P0160': 581718.68125,
 'P0161': 456071.74470000004,
 'P0162': 175422.212792,
 'P0163': 19926.637056,
 'P0164': 56846.697512,
 'P0165': 22767.36756,
 'P0166': 70325.851362,
 'P0167': 24138.019008,
 'P0168': 245350.47885599997,
 'P0169': 31104.695847000006,
 'P0170': 347668.84152,
 'P0171': 56922.669081,
 'P0172': 20299.61808,
 'P0173': 212688.562974,
 'P0174': 16706.813508000003,
 'P0175': 29291.51645,
 'P0176': 97601.38983,
 'P0177': 76803.70788999999,
 'P0178': 293511.72856,
 'P0179': 42662.741002,
 'P0180': 63386.42436,
 'P0181': 101892.2366,
 'P0182': 15946.239744,
 'P0183': 61900.06829999999,
 'P0184': 375551.400168,
 'P0185': 88814.44000799998,
 'P0186': 180998.415,
 'P0187': 91880.27662799999,
 'P0188': 111327.597312,
 'P0189': 83149.789632,
 'P0190': 114531.086538,
 'P0191': 10331.660590000001,
 'P0192': 131931.918336,
 'P0193': 126230.99250000001,
 'P0194': 566704.9722,
 'P0195': 22138.378788,
 'P0196': 40800.186,
 'P0197': 276965.031456,
 'P0198': 7521.790793999999,
 'P0199': 69264.660702,
 'P0200': 276273.14400000003,
 'P0201': 70298.62154400001,
 'P0202': 16892.87292,
 'P0203': 18769.723140000002,
 'P0204': 56767.08899399999,
 'P0205': 122101.105284,
 'P0206': 187182.37625600002,
 'P0207': 202507.99054199998,
 'P0208': 36253.357272,
 'P0209': 35088.444383999995,
 'P0210': 197785.232064,
 'P0211': 170846.86211999998,
 'P0212': 21223.662300000004,
 'P0213': 53835.095691,
 'P0214': 5284.399872000001,
 'P0215': 3879.526013999999,
 'P0216': 14949.990104999997,
 'P0217': 221560.58734200004,
 'P0218': 16422.156422,
 'P0219': 234629.79170399997,
 'P0220': 48020.948919999995,
 'P0221': 252841.3524,
 'P0222': 354012.835176,
 'P0223': 2700.228132,
 'P0224': 145206.07806,
 'P0225': 136754.41026,
 'P0226': 74763.99897,
 'P0227': 454007.3664,
 'P0228': 30414.836064000006,
 'P0229': 32051.598588,
 'P0230': 100292.67685200002,
 'P0231': 301105.91001600004,
 'P0232': 128600.03531999998,
 'P0233': 151749.41235300002,
 'P0234': 171500.932125,
 'P0235': 39150.623459999995,
 'P0236': 80665.50863400001,
 'P0237': 47649.16833600001,
 'P0238': 141411.56106,
 'P0239': 39129.122559999996,
 'P0240': 118061.875,
 'P0241': 71352.129024,
 'P0242': 152857.142438,
 'P0243': 20385.522465000002,
 'P0244': 93753.914128,
 'P0245': 165068.509472,
 'P0246': 184251.834,
 'P0247': 42627.799296,
 'P0248': 43992.52704000001,
 'P0249': 286915.23926,
 'P0250': 241691.18019100002,
 'P0251': 18778.584744,
 'P0252': 160525.37088,
 'P0253': 207849.88224,
 'P0254': 9278.51694,
 'P0255': 111559.613058,
 'P0256': 183050.46486999997,
 'P0257': 52678.794825,
 'P0258': 177237.97833600003,
 'P0259': 456805.642125,
 'P0260': 43497.576624,
 'P0261': 252400.90550000002,
 'P0262': 4784.862532,
 'P0263': 72895.51684800001,
 'P0264': 537886.734552,
 'P0265': 11956.587552,
 'P0266': 18441.172749999998,
 'P0267': 392627.84002099995,
 'P0268': 90734.8266,
 'P0269': 57755.279582,
 'P0270': 35785.9376,
 'P0271': 2637.090484,
 'P0272': 280222.281352,
 'P0273': 41084.378895,
 'P0274': 215123.05813,
 'P0275': 198604.970817,
 'P0276': 236952.09681000002,
 'P0277': 52201.51691,
 'P0278': 169330.93274999998,
 'P0279': 382111.17811200005,
 'P0280': 456664.84495999996,
 'P0281': 120297.94233600001,
 'P0282': 22499.981862,
 'P0283': 151578.402894,
 'P0284': 196701.9475,
 'P0285': 40216.651902,
 'P0286': 27022.390824000002,
 'P0287': 76644.51847499999,
 'P0288': 422220.869652,
 'P0289': 103714.223844,
 'P0290': 38910.604760999995,
 'P0291': 11465.498976000003,
 'P0292': 27239.186258,
 'P0293': 430006.4346,
 'P0294': 11074.920912,
 'P0295': 280913.548664,
 'P0296': 347110.14057299995,
 'P0297': 52745.212296,
 'P0298': 432555.427584,
 'P0299': 27022.601592,
 'P0300': 272251.451136,
 'P0301': 36895.84541999999,
 'P0302': 12220.329300000001,
 'P0303': 13833.79224,
 'P0304': 15059.926169999999,
 'P0305': 82435.83732000002,
 'P0306': 192698.62403999997,
 'P0307': 104924.267916,
 'P0308': 70975.29632699999,
 'P0309': 78704.085768,
 'P0310': 110503.18925800001,
 'P0311': 616219.1931300001,
 'P0312': 5225.204951999999,
 'P0313': 171108.8369,
 'P0314': 372355.57164,
 'P0315': 70559.548422,
 'P0316': 35566.912593,
 'P0317': 18994.851000000002,
 'P0318': 16657.482096,
 'P0319': 99787.24809200001,
 'P0320': 64258.52877999999,
 'P0321': 324395.399916,
 'P0322': 17468.121285,
 'P0323': 6881.94078,
 'P0324': 164288.68659,
 'P0325': 82161.135434,
 'P0326': 82999.212016,
 'P0327': 75557.932688,
 'P0328': 196625.18501999998,
 'P0329': 589777.680114,
 'P0330': 296923.77900000004,
 'P0331': 313050.16767600004,
 'P0332': 25041.778361999997,
 'P0333': 280314.77102000004,
 'P0334': 19731.460686000002,
 'P0335': 51287.129712,
 'P0336': 13253.9012,
 'P0337': 369635.616526,
 'P0338': 203695.88400000002,
 'P0339': 108173.669076,
 'P0340': 37250.246202,
 'P0341': 70343.89619399999,
 'P0342': 199936.67226,
 'P0343': 84782.64816000001,
 'P0344': 57586.14765,
 'P0345': 125222.43333600002,
 'P0346': 92695.293908,
 'P0347': 61270.805068,
 'P0348': 164371.823196,
 'P0349': 140189.5944,
 'P0350': 221703.752,
 'P0351': 64949.731974,
 'P0352': 115032.544011,
 'P0353': 307811.5425,
 'P0354': 318694.677504,
 'P0355': 38786.629284,
 'P0356': 3075.9300000000003,
 'P0357': 380070.85792000004,
 'P0358': 148051.206432,
 'P0359': 19985.452032,
 'P0360': 11546.153073,
 'P0361': 97852.84271499999,
 'P0362': 36198.06084,
 'P0363': 382236.79874,
 'P0364': 146632.3155,
 'P0365': 169894.46259399998,
 'P0366': 5925.883536,
 'P0367': 73877.90591999999,
 'P0368': 184152.0435,
 'P0369': 32256.494424,
 'P0370': 212258.73784500003,
 'P0371': 168998.76593599998,
 'P0372': 3577.4833999999996,
 'P0373': 187674.35529600002,
 'P0374': 22345.547328000004,
 'P0375': 102948.60887999999,
 'P0376': 34120.224319999994,
 'P0377': 20548.484384999996,
 'P0378': 96994.91735999999,
 'P0379': 27363.658139999992,
 'P0380': 190549.59622399998,
 'P0381': 129604.56947999999,
 'P0382': 481992.833308,
 'P0383': 210633.657576,
 'P0384': 128158.51365000001,
 'P0385': 22783.311599999997,
 'P0386': 56368.829159999994,
 'P0387': 19589.000145,
 'P0388': 34032.999375,
 'P0389': 63822.51472499999,
 'P0390': 342356.151456,
 'P0391': 58684.32216,
 'P0392': 180065.024568,
 'P0393': 474075.84751999995,
 'P0394': 390162.051096,
 'P0395': 77955.009216,
 'P0396': 735999.0515360001,
 'P0397': 344617.056,
 'P0398': 156100.369152,
 'P0399': 38351.467476,
 'P0400': 57229.794023999995,
 'P0401': 34228.458792,
 'P0402': 246285.796675,
 'P0403': 39515.488738,
 'P0404': 110756.50324200002,
 'P0405': 482802.16949999996,
 'P0406': 19371.93984,
 'P0407': 17898.037084000003,
 'P0408': 75143.208973,
 'P0409': 79632.019474,
 'P0410': 393679.43351999996,
 'P0411': 165879.31464,
 'P0412': 371581.87789800006,
 'P0413': 20161.621116,
 'P0414': 60079.21919999999,
 'P0415': 23284.377998,
 'P0416': 340827.30090000003,
 'P0417': 8382.945923000001,
 'P0418': 186187.611291,
 'P0419': 130179.378637,
 'P0420': 45515.22706500001,
 'P0421': 15523.354349999998,
 'P0422': 8618.704992,
 'P0423': 454035.317504,
 'P0424': 33921.146819999994,
 'P0425': 132650.96448,
 'P0426': 72541.93293,
 'P0427': 16557.389939999997,
 'P0428': 15636.085783999999,
 'P0429': 7745.393999999999,
 'P0430': 330156.236943,
 'P0431': 37267.66913999999,
 'P0432': 157525.48961599998,
 'P0433': 24592.377996,
 'P0434': 20154.442752,
 'P0435': 294373.63116,
 'P0436': 34740.40534800001,
 'P0437': 100409.188926,
 'P0438': 82510.429648,
 'P0439': 20164.374539999997,
 'P0440': 58522.1,
 'P0441': 24143.10288,
 'P0442': 169247.286138,
 'P0443': 56956.6875,
 'P0444': 58613.327999999994,
 'P0445': 247794.2984,
 'P0446': 16160.588174999999,
 'P0447': 261583.668812,
 'P0448': 341162.06778,
 'P0449': 273279.48081000004,
 'P0450': 109018.80612,
 'P0451': 16728.189465,
 'P0452': 60941.06116800001,
 'P0453': 328594.97390000004,
 'P0454': 100437.81854400001,
 'P0455': 31641.205392000003,
 'P0456': 15887.460204000003,
 'P0457': 159655.93319399995,
 'P0458': 71703.766484,
 'P0459': 66788.4189,
 'P0460': 74378.168448,
 'P0461': 382377.3178,
 'P0462': 54074.609992,
 'P0463': 57380.30811,
 'P0464': 179613.360927,
 'P0465': 30551.770807999997,
 'P0466': 294333.283112,
 'P0467': 178762.93793699998,
 'P0468': 13232.653056,
 'P0469': 340584.98445900006,
 'P0470': 35291.989868000004,
 'P0471': 203971.85809,
 'P0472': 45312.8802,
 'P0473': 146751.7636,
 'P0474': 356590.29609,
 'P0475': 28850.390219999997,
 'P0476': 23642.862880000004,
 'P0477': 73382.635851,
 'P0478': 188429.55804,
 'P0479': 500230.94843000005,
 'P0480': 310510.246868,
 'P0481': 277755.889152,
 'P0482': 100682.35775999998,
 'P0483': 40811.827979999995,
 'P0484': 39752.156559999996,
 'P0485': 28555.723554999997,
 'P0486': 66035.014584,
 'P0487': 106849.652472,
 'P0488': 8762.324736,
 'P0489': 51848.8593,
 'P0490': 23484.217849999997,
 'P0491': 357558.74056,
 'P0492': 177473.208192,
 'P0493': 174165.990126,
 'P0494': 46735.076090999995,
 'P0495': 40327.052575999995,
 'P0496': 35048.42733,
 'P0497': 60844.416984,
 'P0498': 278647.160454,
 'P0499': 22829.453159999994,
 'P0500': 2150.22834,
 'P0501': 32019.155576999998,
 'P0502': 1982.0380440000001,
 'P0503': 28616.981861999997,
 'P0504': 186357.69165599998,
 'P0505': 47501.902500000004,
 'P0506': 557828.6251320001,
 'P0507': 239467.70718,
 'P0508': 70906.453224,
 'P0509': 202813.73784000002,
 'P0510': 20648.541119999998,
 'P0511': 26959.557589999997,
 'P0512': 47577.313596,
 'P0513': 53090.125452,
 'P0514': 147420.49140000003,
 'P0515': 122734.05984,
 'P0516': 560021.61501,
 'P0517': 63091.35419699999,
 'P0518': 36595.807326,
 'P0519': 248014.27622399994,
 'P0520': 25909.402661999997,
 'P0521': 116691.1808,
 'P0522': 2063.0412,
 'P0523': 159720.58035200002,
 'P0524': 186710.37404999998,
 'P0525': 313353.10592,
 'P0526': 77354.352543,
 'P0527': 336257.4963,
 'P0528': 105440.56536000001,
 'P0529': 540810.0679680001,
 'P0530': 697184.93298,
 'P0531': 47909.968590000004,
 'P0532': 27454.708710000003,
 'P0533': 15814.442123999997,
 'P0534': 55844.685432000006,
 'P0535': 59610.103595,
 'P0536': 14121.42714,
 'P0537': 61682.807816,
 'P0538': 109316.75932800001,
 'P0539': 58600.568148,
 'P0540': 32182.288500000002,
 'P0541': 273352.8386400001,
 'P0542': 280158.344104,
 'P0543': 42177.948449999996,
 'P0544': 76851.1296,
 'P0545': 321373.949568,
 'P0546': 6759.823175,
 'P0547': 68127.63132,
 'P0548': 64208.9115,
 'P0549': 287556.756712,
 'P0550': 192905.826724,
 'P0551': 172933.421644,
 'P0552': 55010.59146000001,
 'P0553': 178381.89564,
 'P0554': 10822.290776,
 'P0555': 132260.09731200003,
 'P0556': 257475.77049600004,
 'P0557': 255640.301304,
 'P0558': 449180.16000000003,
 'P0559': 95100.09593,
 'P0560': 12652.16876,
 'P0561': 167471.56615499998,
 'P0562': 30151.134468,
 'P0563': 274528.82222999993,
 'P0564': 28234.404000000002,
 'P0565': 5252.292864000001,
 'P0566': 86757.682527,
 'P0567': 181275.691905,
 'P0568': 84252.674016,
 'P0569': 149594.947322,
 'P0570': 40965.60115199999,
 'P0571': 7540.814047,
 'P0572': 83462.96574,
 'P0573': 17853.71328,
 'P0574': 118735.06279599998,
 'P0575': 41815.505452,
 'P0576': 219221.04701,
 'P0577': 21037.400516,
 'P0578': 133165.800504,
 'P0579': 304569.700266,
 'P0580': 125179.32039599998,
 'P0581': 108993.85728,
 'P0582': 154635.90011999998,
 'P0583': 11949.88014,
 'P0584': 306183.4776,
 'P0585': 36202.375143000005,
 'P0586': 46847.993303999996,
 'P0587': 43625.588736,
 'P0588': 80078.850108,
 'P0589': 25583.908979999997,
 'P0590': 309641.1896,
 'P0591': 108886.45521600002,
 'P0592': 34655.432850000005,
 'P0593': 8967.518909999999,
 'P0594': 44220.8096,
 'P0595': 32731.58452,
 'P0596': 106225.03710000002,
 'P0597': 272091.16539,
 'P0598': 6213.266850000001,
 'P0599': 769703.1167480001,
 'P0600': 320657.022918,
 'P0601': 54437.586546,
 'P0602': 7800.3180360000015,
 'P0603': 40199.63374,
 'P0604': 66821.339874,
 'P0605': 7110.612984000001,
 'P0606': 8984.164612,
 'P0607': 124391.778364,
 'P0608': 48601.638042000006,
 'P0609': 522188.0136,
 'P0610': 357468.01456499996,
 'P0611': 326293.74646000005,
 'P0612': 47538.21006,
 'P0613': 114076.72892,
 'P0614': 24521.801830000004,
 'P0615': 38116.001986,
 'P0616': 1720.2024000000004,
 'P0617': 25041.413460999996,
 'P0618': 19725.610536,
 'P0619': 185454.90418399998,
 'P0620': 292527.376064,
 'P0621': 64057.47855000001,
 'P0622': 4253.645759999999,
 'P0623': 7913.753535999999,
 'P0624': 5818.2637239999995,
 'P0625': 22496.810699999998,
 'P0626': 44488.855908,
 'P0627': 368478.13643199997,
 'P0628': 31355.87184,
 'P0629': 95983.88262399999,
 'P0630': 244743.339225,
 'P0631': 25806.459756000004,
 'P0632': 87596.34283400001,
 'P0633': 66786.915096,
 'P0634': 438683.79744000005,
 'P0635': 260042.685084,
 'P0636': 471608.829824,
 'P0637': 379590.73653600004,
 'P0638': 141116.98824,
 'P0639': 82817.16162,
 'P0640': 55821.645599999996,
 'P0641': 42558.014912,
 'P0642': 182766.64174000002,
 'P0643': 522081.4553460001,
 'P0644': 51034.583208,
 'P0645': 190108.15488,
 'P0646': 261181.60561800003,
 'P0647': 51178.93081199999,
 'P0648': 360036.26984,
 'P0649': 202038.869088,
 'P0650': 220256.71332,
 'P0651': 53526.745584000004,
 'P0652': 138626.131644,
 'P0653': 23628.339000000004,
 'P0654': 28129.114053,
 'P0655': 66375.40060000001,
 'P0656': 400972.88574,
 'P0657': 338256.30565999995,
 'P0658': 125087.01370000002,
 'P0659': 495992.77836399997,
 'P0660': 4059.3066799999997,
 'P0661': 175319.568396,
 'P0662': 83355.19520999999,
 'P0663': 163082.86575000003,
 'P0664': 164276.286048,
 'P0665': 133973.32158,
 'P0666': 95587.667712,
 'P0667': 418676.81203399994,
 'P0668': 65321.07004500001,
 'P0669': 97507.454928,
 'P0670': 74005.31685599999,
 'P0671': 36199.566144000004,
 'P0672': 12024.908,
 'P0673': 403821.99442000006,
 'P0674': 105845.21164800001,
 'P0675': 16564.203216,
 'P0676': 756973.9513600001,
 'P0677': 142564.51352,
 'P0678': 203937.64383999998,
 'P0679': 323066.348532,
 'P0680': 363004.15788,
 'P0681': 75019.29827500001,
 'P0682': 174612.46508999998,
 'P0683': 53228.50536599999,
 'P0684': 207318.23408,
 'P0685': 12438.316799999999,
 'P0686': 261366.08255999998,
 'P0687': 170746.44220800002,
 'P0688': 104797.885104,
 'P0689': 73796.2368,
 'P0690': 454706.73561599996,
 'P0691': 14570.289535999998,
 'P0692': 33491.024896,
 'P0693': 38662.668432,
 'P0694': 107689.44936399999,
 'P0695': 12487.841245,
 'P0696': 108164.98692999998,
 'P0697': 404168.57817,
 'P0698': 299019.05510399997,
 'P0699': 271024.359991,
 'P0700': 81714.140744,
 'P0701': 267426.89881600003,
 'P0702': 137302.37521,
 'P0703': 69344.77484799999,
 'P0704': 147049.535592,
 'P0705': 166834.10640599998,
 'P0706': 339340.13749999995,
 'P0707': 192127.785588,
 'P0708': 4219.769069999999,
 'P0709': 113170.52175000001,
 'P0710': 31700.32551000001,
 'P0711': 627868.863369,
 'P0712': 16704.203392,
 'P0713': 442501.62479999993,
 'P0714': 92735.471328,
 'P0715': 8687.759685,
 'P0716': 50364.589521,
 'P0717': 63626.183386,
 'P0718': 284748.045516,
 'P0719': 317953.95830999996,
 'P0720': 382513.57707,
 'P0721': 4864.381368,
 'P0722': 188814.98813,
 'P0723': 19543.827875,
 'P0724': 13164.087972,
 'P0725': 164726.871726,
 'P0726': 52701.787986999996,
 'P0727': 91424.996784,
 'P0728': 35185.635012,
 'P0729': 139553.285634,
 'P0730': 27391.434264,
 'P0731': 185869.21651199998,
 'P0732': 679003.9589519999,
 'P0733': 33599.79176,
 'P0734': 103493.46635400002,
 'P0735': 66561.47189999999,
 'P0736': 161511.77196000004,
 'P0737': 33778.972345,
 'P0738': 7254.4602239999995,
 'P0739': 117469.66265999999,
 'P0740': 88796.979648,
 'P0741': 100702.80352,
 'P0742': 45676.807272,
 'P0743': 67400.54685,
 'P0744': 11390.58578,
 'P0745': 36009.48,
 'P0746': 345222.578776,
 'P0747': 40994.720448,
 'P0748': 75835.375445,
 'P0749': 50320.090963999995,
 'P0750': 83118.05675199999,
 'P0751': 1006.1869760000002,
 'P0752': 148787.497404,
 'P0753': 100981.791456,
 'P0754': 53335.414748,

In [22]:
df_prices = pd.DataFrame.from_dict(prices, orient='index', columns=['volume'])
print(df_prices.shape)
df_prices.head()

(1000, 1)

              volume
P0001   48469.098690
P0002   11252.963820
P0003   24725.379063
P0004    8361.648240
P0005  255200.667150

#### Aggregate

In [23]:
data = pd.merge(data, df_prices, left_index=True, right_index=True, how='left')
data

,store_name,mass,dimension_length,dimension_width,dimension_height,days_since_last_purchase,package_volume,stock_age,quantity_sold,last_modified,volume
item_code,,,,,,,,,,,
P0019,CityMart,2.81,26.83,38.75,24.89,323,25877.199625,253,202,2023-01-19,21814.067016
P0024,CityMart,3.3,59.23,34.99,21.78,321,45138.128706,21,225,2023-01-24,80893.196160
P0025,CityMart,2.34,22.6,16.9,60.12,291,22962.2328,316,278,2023-01-25,87468.086418
P0034,CityMart,6.54,18.59,68.72,21.99,126,28092.330552,612,233,2023-02-03,6635.396628
P0039,CityMart,9.94,57.89,88.33,35.45,312,181270.870165,968,203,2023-02-08,170846.537576
...,...,...,...,...,...,...,...,...,...,...,...
P1978,HighStreet_Bazaar,6.28,72.48,47.71,83.54,322.0,288883.057632,637,235,1843344000000,NaN
P1981,HighStreet_Bazaar,0.91,31.13,55.22,71.22,342.0,122427.080292,60,241,1843603200000,NaN
P1982,HighStreet_Bazaar,4.65,65.72,82.01,60.75,192.0,327424.1049,925,237,1843689600000,NaN
P1987,HighStreet_Bazaar,4.64,93.41,52.53,41.02,131.0,201278.055846,317,256,1844121600000,NaN
P1994,HighStreet_Bazaar,5.43,11.2,56.52,14.73,128.0,9324.44352,315,287,1844726400000,NaN

In [24]:
get_simple_baseline(data, fillna_value=-1, drop_cols=['store_name', 'last_modified'], k_fold=5, scaler='standard', model='linear', metric='mae', target_col='quantity_sold')

45.04524298046092

### Scrapping sources

In [25]:
%pip install selenium bs4

from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time

# Set up the Selenium WebDriver (e.g., Chrome)
driver = webdriver.Chrome()  # Make sure ChromeDriver is installed
# driver = webdriver.Firefox()
# driver = webdriver.Edge()
# driver = webdriver.Safari()

# Open the URL
url = 'https://www.raphaelcousin.com/module4/scrapable-data'
driver.get(url)

# Wait for the page to fully load (increase time if needed)
time.sleep(5)

# Get the fully rendered page source
html = driver.page_source

# Parse the HTML with BeautifulSoup
soup = BeautifulSoup(html, 'html.parser')

# Initialize lists to store scraped data
exercise_data = []

# Find both tables
tables = soup.find_all('table')

# Close the Selenium WebDriver
driver.quit()

# Scrape the second table (Exercise Data)
course_table = tables[1]
for row in course_table.find('tbody').find_all('tr'):
    cols = row.find_all('td')
    #exercise_data.append({ TODO })
    exercise_data.append({
        'Item Code' : cols[0].text,
        'Customer Score' : int(cols[1].text),
        'Total Reviews' : int(cols[2].text),
        'Updated Timestamp' : int(cols[3].text)
    })


# Convert the lists to pandas DataFrames
df_exercise = pd.DataFrame(exercise_data)
df_exercise.head()

Requirement already satisfied: selenium in d:\anaconda\lib\site-packages (4.35.0)
Requirement already satisfied: bs4 in d:\anaconda\lib\site-packages (0.0.2)
Requirement already satisfied: urllib3<3.0,>=2.5.0 in d:\anaconda\lib\site-packages (from urllib3[socks]<3.0,>=2.5.0->selenium) (2.5.0)
Requirement already satisfied: trio~=0.30.0 in d:\anaconda\lib\site-packages (from selenium) (0.30.0)
Requirement already satisfied: trio-websocket~=0.12.2 in d:\anaconda\lib\site-packages (from selenium) (0.12.2)
Requirement already satisfied: certifi>=2025.6.15 in d:\anaconda\lib\site-packages (from selenium) (2025.8.3)
Requirement already satisfied: typing_extensions~=4.14.0 in d:\anaconda\lib\site-packages (from selenium) (4.14.1)
Requirement already satisfied: websocket-client~=1.8.0 in d:\anaconda\lib\site-packages (from selenium) (1.8.0)
Requirement already satisfied: beautifulsoup4 in d:\anaconda\lib\site-packages (from bs4) (4.12.3)
Requirement already satisfied: attrs>=23.2.0 in d:\anaconda\lib\site-packages (from trio~=0.30.0->selenium) (25.3.0)
Requirement already satisfied: sortedcontainers in d:\anaconda\lib\site-packages (from trio~=0.30.0->selenium) (2.4.0)
Requirement already satisfied: idna in d:\anaconda\lib\site-packages (from trio~=0.30.0->selenium) (3.7)
Requirement already satisfied: outcome in d:\anaconda\lib\site-packages (from trio~=0.30.0->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in d:\anaconda\lib\site-packages (from trio~=0.30.0->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in d:\anaconda\lib\site-packages (from trio~=0.30.0->selenium) (1.17.1)
Requirement already satisfied: wsproto>=0.14 in d:\anaconda\lib\site-packages (from trio-websocket~=0.12.2->selenium) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in d:\anaconda\lib\site-packages (from urllib3[socks]<3.0,>=2.5.0->selenium) (1.7.1)
Requirement already satisfied: soupsieve>1.2 in d:\anaconda\lib\site-packages (from beautifulsoup4->bs4) (2.5)
Requirement already satisfied: pycparser in d:\anaconda\lib\site-packages (from cffi>=1.14->trio~=0.30.0->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in d:\anaconda\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.12.2->selenium) (0.14.0)
Note: you may need to restart the kernel to use updated packages.

  Item Code  Customer Score  Total Reviews  Updated Timestamp
0     P0001               2            972            1728524
1     P0002               3            260            1728562
2     P0003               2            285            1728577
3     P0004               5            512            1728528
4     P0005               3             85            1728512

In [26]:
df_exercise.columns = [col.lower() for col in df_exercise.columns]
df_exercise.columns = df_exercise.columns.str.replace(' ', '_')
df_exercise.set_index('item_code', inplace=True)
print(df_exercise.shape)

(2000, 3)

#### Aggregate

In [27]:
data = pd.merge(data, df_exercise, left_index=True, right_index=True, how='left')
data.head()

,store_name,mass,dimension_length,dimension_width,dimension_height,days_since_last_purchase,package_volume,stock_age,quantity_sold,last_modified,volume,customer_score,total_reviews,updated_timestamp
item_code,,,,,,,,,,,,,,
P0019,CityMart,2.81,26.83,38.75,24.89,323,25877.199625,253,202,2023-01-19,21814.067016,1,948,1728484
P0024,CityMart,3.3,59.23,34.99,21.78,321,45138.128706,21,225,2023-01-24,80893.196160,3,436,1728580
P0025,CityMart,2.34,22.6,16.9,60.12,291,22962.2328,316,278,2023-01-25,87468.086418,5,703,1728494
P0034,CityMart,6.54,18.59,68.72,21.99,126,28092.330552,612,233,2023-02-03,6635.396628,2,935,1728525
P0039,CityMart,9.94,57.89,88.33,35.45,312,181270.870165,968,203,2023-02-08,170846.537576,2,188,1728527

In [33]:
get_simple_baseline(data, fillna_value=-1, drop_cols=['store_name', 'last_modified'], k_fold=5, scaler='standard', model='linear', metric='mae', target_col='quantity_sold')

41.51966936431067

### Generating Submission File

In [29]:
# X_test =  read  Neighborhood_Market_data

# read
df_StoreN =  pd.read_csv("Neighborhood_Market_data.csv", sep=",", index_col='item_code')
df_StoreN

,store_name,mass,dimension_length,dimension_width,dimension_height,days_since_last_purchase,package_volume,stock_age,last_modified
item_code,,,,,,,,,
P0002,Neighborhood_Market,5.51,51.79,46.72,72.02,344,174261.666176,287,2023-01-02
P0004,Neighborhood_Market,3.97,84.63,39.42,42.46,189,141651.425916,387,2023-01-04
P0005,Neighborhood_Market,5.99,39.33,83.51,5.12,183,16816.375296,382,2023-01-05
P0010,Neighborhood_Market,4.10,77.43,49.56,74.41,208,285543.225828,656,2023-01-10
P0013,Neighborhood_Market,6.96,95.39,34.61,23.24,114,76725.649196,755,2023-01-13
...,...,...,...,...,...,...,...,...,...
P1972,Neighborhood_Market,5.68,17.89,71.87,95.67,296,123008.113881,411,2028-05-25
P1977,Neighborhood_Market,1.53,84.32,64.91,66.30,171,362873.902560,702,2028-05-30
P1991,Neighborhood_Market,7.79,84.46,82.96,52.14,50,365334.635424,190,2028-06-13
P1997,Neighborhood_Market,8.91,66.50,5.79,41.11,336,15828.788850,177,2028-06-19
P1999,Neighborhood_Market,2.03,66.77,60.18,73.20,190,294133.601520,806,2028-06-21

In [34]:
df_StoreN = pd.merge(df_StoreN, df_prices, left_index=True, right_index=True, how='left')
df_StoreN = pd.merge(df_StoreN, df_exercise, left_index=True, right_index=True, how='left')
df_StoreN.head()

,store_name,mass,dimension_length,dimension_width,dimension_height,days_since_last_purchase,package_volume,stock_age,last_modified,volume,customer_score,total_reviews,updated_timestamp
item_code,,,,,,,,,,,,,
P0002,Neighborhood_Market,5.51,51.79,46.72,72.02,344,174261.666176,287,2023-01-02,11252.963820,3,260,1728562
P0004,Neighborhood_Market,3.97,84.63,39.42,42.46,189,141651.425916,387,2023-01-04,8361.648240,5,512,1728528
P0005,Neighborhood_Market,5.99,39.33,83.51,5.12,183,16816.375296,382,2023-01-05,255200.667150,3,85,1728512
P0010,Neighborhood_Market,4.10,77.43,49.56,74.41,208,285543.225828,656,2023-01-10,746779.532672,2,709,1728500
P0013,Neighborhood_Market,6.96,95.39,34.61,23.24,114,76725.649196,755,2023-01-13,10598.364972,3,984,1728533

In [ ]:
_, x_pred = get_simple_baseline(data, fillna_value=-1, drop_cols=['store_name', 'last_modified'], k_fold=5, scaler='standard', model='linear', metric='mae', target_col='quantity_sold', X_data_test = df_StoreN)
# 返回两个结果：交叉验证平均分，和对X_data_test的预测结果
# 保留x_pred

In [36]:
submission = pd.DataFrame({
    'item_code': df_StoreN.index,
    'quantity_sold': 0 # your_prediction
})

submission.to_csv('submission.csv', index=False, sep=',')
submission.head()

  item_code  quantity_sold
0     P0002              0
1     P0004              0
2     P0005              0
3     P0010              0
4     P0013              0